services:
  - type: web
    name: sih-idr-engine
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: FORCE_CPU
        value: "1"
      - key: IDR_MODEL_DIR
        value: /app/data/preprocessing/experiment_17/checkpoints
